---
settings:
  name: ONTAP tools for VMware vSphere 10.0
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation zu ONTAP Tools für VMware vSphere 10.0
    url: "/index.html"
  - title: Versionshinweise
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: manage
  - section: migrate
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
