---
permalink: manage/update_vcenter_ontap_credentials.html 
sidebar: sidebar 
keywords:  
summary: Sie können die vCenter- und ONTAP-Anmeldedaten über die Wartungskonsole aktualisieren. 
---
= Aktualisieren Sie die vCenter- und ONTAP-Anmeldedaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die vCenter- und ONTAP-Anmeldedaten über die Wartungskonsole aktualisieren.

*Was Sie brauchen*

Sie müssen über die Anmeldedaten des maint-Benutzers verfügen.

*Über diese Aufgabe*

Wenn Sie nach der Bereitstellung die Anmeldeinformationen für vCenter, ONTAP oder Datalif geändert haben, müssen Sie die Anmeldeinformationen mit diesem Verfahren aktualisieren.

*Schritte*

. Öffnen Sie über den vCenter Server eine Konsole für VASA Provider.
. Melden Sie sich als Wartungbenutzer an.
. Eingabe `4` Wählen Sie Support und Diagnose aus.
. Eingabe `1` Wählen Sie Access Diagnostic Shell aus.
. Eingabe `y` Fortfahren.
. Aktualisieren Sie die Anmeldeinformationen nach Bedarf:
+
.. Führen Sie zum Aktualisieren der ONTAP-Anmeldeinformationen den folgenden Befehl aus:
+
--
otv-Update --ontapBenutzername <new username> --ontapPasswort <new password>

--
.. Führen Sie zum Aktualisieren der vCenter-Anmeldeinformationen den folgenden Befehl aus:
+
--
otv-Update --vcenterBenutzername <new username> --vcenterPasswort <new password>

--
.. Führen Sie zum Aktualisieren von datalif den folgenden Befehl aus:
+
--
otv-Update --dataLif <New Datalif IP>

--



